### POST ISSUE
POST http://localhost:3000/api/issues
content-type: application/json

{
    "title": "First Issue",
    "description": "Description of the first issue"
}

###GET
GET http://localhost:3000/


###UPDATE ISSUE
PATCH http://localhost:3000/api/issues/2
content-type: application/json

{
    "title": "Updated Issue 2",
    "description": "Updated description of the issue 2"
}

### DELETE ISSUE
DELETE http://localhost:3000/api/issues/3
